CREATE TABLE ttypes(id number(20) GENERATED BY DEFAULT ON NULL as IDENTITY,
  type varchar2(100) NOT NULL, cell_number varchar2(20) NOT NULL,
  description varchar2(255) NOT NULL, deleted number(1) NOT NULL,
  constraint pk_types_id PRIMARY KEY(id));

CREATE UNIQUE INDEX cell_number_uk ON ttypes(cell_number);
CREATE SEQUENCE types_seq START WITH 1;
