CREATE TABLE tvehicle(id number(20) GENERATED BY DEFAULT ON NULL as IDENTITY,
  name varchar2(20) NOT NULL, model varchar2(50) NOT NULL,
  type varchar2(10) NOT NULL, reg_no varchar2(10) NOT NULL,
  constraint pk_vehicle_id PRIMARY KEY(id));

CREATE UNIQUE INDEX reg_no_uk ON tvehicle(reg_no);
CREATE SEQUENCE vehicle_seq START WITH 1;
